### ISSUE TITLE
Bazel test --batch mode is deprecated

### ISSUE THREAD

**Issue by whuang8** [google/minions#27]
### Issue
When running `bazel test` with the `--batch` flag, bazel outputs deprecation warning messages. These warning messages can be seen [here, in a travis build of master](https://travis-ci.org/google/minions/builds/429420068#L584)

Following [what is stated](https://docs.bazel.build/versions/master/user-manual.html#flag--batch) on the Bazel User Manual, [shutdown](https://docs.bazel.build/versions/master/user-manual.html#shutdown) should be used to explicitly shut down the Bazel server.

**Comment by paradoxengine** [comment]
Thank you very much!
